apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mon-ingress
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - myservice.info
      secretName: myservice-tls
  rules:
    - host: myservice.info
      http:
        paths:
          - path: /service2
            pathType: Prefix
            backend:
              service:
                name: mon-service-2
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mon-service-1
                port:
                  number: 8080